sonar.projectKey=com.universidad:productos-service
sonar.projectName=Productos Service
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/*Application.java
sonar.host.url=http://localhost:9000
sonar.qualitygate.wait=false
